export interface INewGuideConfigStruct{
	key:number; //引导ID
	step:number; //大步骤
	cell:number; //小步骤
	guide_desc:string; //引导描述
	trigger_type:number; //触发类型（仅在第一小步中添加）
	guide_type:number; //引导类型（1:剧情引导，2:软引导，3:强制引导）
	is_skip:number; //执行中是否跳步骤（仅在第一小步中存在）
	direct_make:number; //立即显示触摸遮罩
	mask_threshold:number; //遮罩对透明通道阈值
	vd_name:string; //大弹窗立绘名称
	vd_notify:string; //大弹窗立绘
	vd_direction:{x:number,y:number,scale:number,}; //立绘偏移
	finger:number; //手指
	aperture:number; //光圈
	mask_transparency:number; //遮罩透明度
	plot_text:string; //剧情描述
	is_net:number; //是否是网络步骤
	vd_dire:number; //立绘方向
	show_window:number; //是否显示小弹窗
	window_head:number; //小弹窗人物头像
	window_text:string; //小弹窗对话文本
	dire_shifting:{x:number,y:number,}; //小弹窗位置偏移
};
class NewGuideConfig{  
    private mConfigObject:{[key:number]: INewGuideConfigStruct}  = {};
    private mConfigArray:Array<INewGuideConfigStruct> = new Array<INewGuideConfigStruct>();
    constructor(){
        this.InitConfig();
        this.InitArray();
    }
    private InitConfig():void{
		this.mConfigObject[1] = {key:1,step:1,cell:1,guide_desc:"创角剧情",trigger_type:1,guide_type:1,is_skip:1,direct_make:0,mask_threshold:0,vd_name:"<id=11>？？？</id>",vd_notify:"angel_mojiwang",vd_direction:{x:50,y:100,scale:0.6,},finger:0,aperture:0,mask_transparency:0,plot_text:"<id=10>天命者，如今灾难又起，世下民不聊生，目光所及之处皆是满目疮痍，各大势力彼此虎视眈眈</id>",is_net:0,vd_dire:2,show_window:0,window_head:2,window_text:"",dire_shifting:{x:0,y:0,},};
		this.mConfigObject[2] = {key:2,step:1,cell:2,guide_desc:"创角剧情",trigger_type:1,guide_type:1,is_skip:1,direct_make:0,mask_threshold:0,vd_name:"<id=11>？？？</id>",vd_notify:"angel_mojiwang",vd_direction:{x:50,y:100,scale:0.6,},finger:0,aperture:0,mask_transparency:0,plot_text:"<id=10>不论你之前是如何，即使被选中为天命者，以后的路也要加倍小心，这个世界的稳定就看你了，这后世是盛是衰，且看你是强是弱了，不过，看你确是有这个资质</id>",is_net:0,vd_dire:2,show_window:0,window_head:2,window_text:"",dire_shifting:{x:0,y:0,},};
		this.mConfigObject[3] = {key:3,step:1,cell:3,guide_desc:"创角剧情",trigger_type:1,guide_type:1,is_skip:1,direct_make:0,mask_threshold:0,vd_name:"<id=11>冰海女巫</id>",vd_notify:"draw_aiEr",vd_direction:{x:-150,y:100,scale:0.6,},finger:0,aperture:0,mask_transparency:0,plot_text:"<id=10>主人！主人！！</id>",is_net:0,vd_dire:1,show_window:0,window_head:2,window_text:"",dire_shifting:{x:0,y:0,},};
		this.mConfigObject[4] = {key:4,step:1,cell:4,guide_desc:"创角剧情",trigger_type:1,guide_type:1,is_skip:1,direct_make:0,mask_threshold:0,vd_name:"<id=11>冰海女巫</id>",vd_notify:"draw_aiEr",vd_direction:{x:-150,y:100,scale:0.6,},finger:0,aperture:0,mask_transparency:0,plot_text:"<id=10>主人，你总算醒了~</id>",is_net:0,vd_dire:1,show_window:0,window_head:2,window_text:"",dire_shifting:{x:0,y:0,},};
		this.mConfigObject[5] = {key:5,step:1,cell:5,guide_desc:"创角剧情",trigger_type:1,guide_type:1,is_skip:1,direct_make:0,mask_threshold:0,vd_name:"<id=11>冰海女巫</id>",vd_notify:"draw_aiEr",vd_direction:{x:-150,y:100,scale:0.6,},finger:0,aperture:0,mask_transparency:0,plot_text:"<id=10>什么？你问我为什么叫你主人</id>",is_net:0,vd_dire:1,show_window:0,window_head:2,window_text:"",dire_shifting:{x:0,y:0,},};
		this.mConfigObject[6] = {key:6,step:1,cell:6,guide_desc:"创角剧情",trigger_type:1,guide_type:1,is_skip:1,direct_make:0,mask_threshold:0,vd_name:"<id=11>冰海女巫</id>",vd_notify:"draw_aiEr",vd_direction:{x:-150,y:100,scale:0.6,},finger:0,aperture:0,mask_transparency:0,plot_text:"<id=10>这片大陆名为艾瑞斯加大陆，其中分为多个板块，每个板块都有各自的势力组织，大陆每隔300年就会降临灾难，每到这时就会出现一个强大无比的领导者，重新带领世界走向和平</id>",is_net:0,vd_dire:1,show_window:0,window_head:2,window_text:"",dire_shifting:{x:0,y:0,},};
		this.mConfigObject[7] = {key:7,step:1,cell:7,guide_desc:"创角剧情",trigger_type:1,guide_type:1,is_skip:1,direct_make:0,mask_threshold:0,vd_name:"<id=11>冰海女巫</id>",vd_notify:"draw_aiEr",vd_direction:{x:-150,y:100,scale:0.6,},finger:0,aperture:0,mask_transparency:0,plot_text:"<id=10>我是收到了上任魔界王的指引，在此地等候主人多时了，之后我会尽心辅助主人，这片大陆的信息后续我会慢慢讲给主人</id>",is_net:0,vd_dire:1,show_window:0,window_head:2,window_text:"",dire_shifting:{x:0,y:0,},};
		this.mConfigObject[8] = {key:8,step:1,cell:8,guide_desc:"创角剧情",trigger_type:1,guide_type:1,is_skip:1,direct_make:0,mask_threshold:0,vd_name:"<id=11>冰海女巫</id>",vd_notify:"draw_aiEr",vd_direction:{x:-150,y:100,scale:0.6,},finger:0,aperture:0,mask_transparency:0,plot_text:"<id=10>主人，来到这个新世界，先给自己取个响亮的名称吧，取完名称将会得到天命者的奖励</id>",is_net:0,vd_dire:1,show_window:0,window_head:2,window_text:"",dire_shifting:{x:0,y:0,},};
		this.mConfigObject[9] = {key:9,step:1,cell:9,guide_desc:"取名界面",trigger_type:1,guide_type:2,is_skip:1,direct_make:1,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:0,mask_transparency:0,plot_text:"",is_net:0,vd_dire:1,show_window:0,window_head:2,window_text:"",dire_shifting:{x:0,y:0,},};
		this.mConfigObject[10] = {key:10,step:1,cell:10,guide_desc:"恭喜获得",trigger_type:1,guide_type:2,is_skip:1,direct_make:1,mask_threshold:1,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:0,mask_transparency:0,plot_text:"",is_net:0,vd_dire:1,show_window:0,window_head:2,window_text:"",dire_shifting:{x:0,y:0,},};
		this.mConfigObject[11] = {key:11,step:2,cell:1,guide_desc:"注入剧情1",trigger_type:1,guide_type:1,is_skip:1,direct_make:0,mask_threshold:0,vd_name:"<id=11>冰海女巫</id>",vd_notify:"draw_aiEr",vd_direction:{x:-150,y:100,scale:0.6,},finger:0,aperture:0,mask_transparency:0,plot_text:"<id=10>主人，取完名称了可以准备开始第一场战斗了</id>",is_net:0,vd_dire:1,show_window:0,window_head:2,window_text:"",dire_shifting:{x:0,y:0,},};
		this.mConfigObject[12] = {key:12,step:2,cell:2,guide_desc:"注入剧情2",trigger_type:1,guide_type:1,is_skip:1,direct_make:0,mask_threshold:0,vd_name:"<id=11>冰海女巫</id>",vd_notify:"draw_aiEr",vd_direction:{x:-150,y:100,scale:0.6,},finger:0,aperture:0,mask_transparency:0,plot_text:"<id=10>不过，这片大陆的英雄都因为魔龙王引发的战乱丢失了自身的绝技</id>",is_net:0,vd_dire:1,show_window:0,window_head:2,window_text:"",dire_shifting:{x:0,y:0,},};
		this.mConfigObject[13] = {key:13,step:2,cell:3,guide_desc:"注入剧情3",trigger_type:1,guide_type:1,is_skip:1,direct_make:0,mask_threshold:0,vd_name:"<id=11>冰海女巫</id>",vd_notify:"draw_aiEr",vd_direction:{x:-150,y:100,scale:0.6,},finger:0,aperture:0,mask_transparency:0,plot_text:"<id=10>主人需要给每个英雄装配技能才能正式参加战斗，从而协助主人</id>",is_net:0,vd_dire:1,show_window:0,window_head:2,window_text:"",dire_shifting:{x:0,y:0,},};
		this.mConfigObject[14] = {key:14,step:2,cell:4,guide_desc:"点击主城英雄按钮",trigger_type:1,guide_type:3,is_skip:1,direct_make:0,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:1,mask_transparency:125,plot_text:"",is_net:0,vd_dire:1,show_window:1,window_head:2,window_text:"<id=12>下面去给看看英雄界面吧，刚刚获得了好多奖励！</id>",dire_shifting:{x:-400,y:-500,},};
		this.mConfigObject[15] = {key:15,step:2,cell:5,guide_desc:"点击冰海女巫",trigger_type:1,guide_type:3,is_skip:1,direct_make:1,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:1,mask_transparency:125,plot_text:"",is_net:0,vd_dire:1,show_window:1,window_head:2,window_text:"<id=12>选择英雄查看详情界面</id>",dire_shifting:{x:-350,y:0,},};
		this.mConfigObject[16] = {key:16,step:2,cell:6,guide_desc:"点击技能按钮",trigger_type:1,guide_type:3,is_skip:1,direct_make:1,mask_threshold:1,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:1,mask_transparency:125,plot_text:"",is_net:0,vd_dire:1,show_window:1,window_head:2,window_text:"<id=12>点击下方页签查看英雄技能详情</id>",dire_shifting:{x:-150,y:-400,},};
		this.mConfigObject[17] = {key:17,step:2,cell:7,guide_desc:"点击技能1",trigger_type:1,guide_type:4,is_skip:1,direct_make:1,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:0,mask_transparency:125,plot_text:"",is_net:0,vd_dire:1,show_window:1,window_head:2,window_text:"<id=12>每个英雄都可以装配三个技能，这是主动技能</id>",dire_shifting:{x:-400,y:-50,},};
		this.mConfigObject[18] = {key:18,step:2,cell:8,guide_desc:"点击技能2",trigger_type:1,guide_type:4,is_skip:1,direct_make:1,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:0,mask_transparency:125,plot_text:"",is_net:0,vd_dire:1,show_window:1,window_head:2,window_text:"<id=12>这里核心技能，拥有非常强大的技能效果</id>",dire_shifting:{x:-200,y:-100,},};
		this.mConfigObject[19] = {key:19,step:2,cell:9,guide_desc:"点击技能3",trigger_type:1,guide_type:4,is_skip:1,direct_make:1,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:0,mask_transparency:125,plot_text:"",is_net:0,vd_dire:1,show_window:1,window_head:2,window_text:"<id=12>这是被动技能，好的被动技能可以极大强化自身</id>",dire_shifting:{x:-150,y:-50,},};
		this.mConfigObject[20] = {key:20,step:2,cell:10,guide_desc:"点击技能4",trigger_type:1,guide_type:4,is_skip:1,direct_make:1,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:0,mask_transparency:125,plot_text:"",is_net:0,vd_dire:1,show_window:1,window_head:2,window_text:"<id=12>这里是套装技能，满足套装条件后可以激活</id>",dire_shifting:{x:-300,y:-250,},};
		this.mConfigObject[21] = {key:21,step:2,cell:11,guide_desc:"装配指引（点击技能1）",trigger_type:1,guide_type:3,is_skip:1,direct_make:1,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:1,mask_transparency:125,plot_text:"",is_net:0,vd_dire:1,show_window:1,window_head:2,window_text:"<id=12>为英雄装配上技能</id>",dire_shifting:{x:-400,y:-50,},};
		this.mConfigObject[22] = {key:22,step:2,cell:12,guide_desc:"点击三星页签",trigger_type:1,guide_type:3,is_skip:1,direct_make:1,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:1,mask_transparency:125,plot_text:"",is_net:0,vd_dire:1,show_window:1,window_head:2,window_text:"<id=12>技能分为不同品质，点击切换</id>",dire_shifting:{x:-250,y:-350,},};
		this.mConfigObject[23] = {key:23,step:2,cell:13,guide_desc:"选择技能",trigger_type:1,guide_type:3,is_skip:1,direct_make:1,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:1,mask_transparency:125,plot_text:"",is_net:2,vd_dire:1,show_window:1,window_head:2,window_text:"<id=12>选择技能装配</id>",dire_shifting:{x:-150,y:-50,},};
		this.mConfigObject[24] = {key:24,step:2,cell:14,guide_desc:"空白提示",trigger_type:1,guide_type:4,is_skip:1,direct_make:1,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:0,mask_transparency:0,plot_text:"",is_net:0,vd_dire:1,show_window:1,window_head:2,window_text:"<id=12>主人可以根据不同英雄属性选择技能搭配，凑齐技能套装变强有事半功倍的效果</id>",dire_shifting:{x:-400,y:-50,},};
		this.mConfigObject[25] = {key:25,step:3,cell:1,guide_desc:"点击闯关",trigger_type:1,guide_type:3,is_skip:1,direct_make:0,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:1,mask_transparency:125,plot_text:"",is_net:0,vd_dire:1,show_window:1,window_head:2,window_text:"<id=12>先点击前往战斗界面，这里就是我们以后主要的战斗场地</id>",dire_shifting:{x:-250,y:-500,},};
		this.mConfigObject[26] = {key:26,step:3,cell:2,guide_desc:"点击挑战",trigger_type:1,guide_type:3,is_skip:1,direct_make:1,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:1,mask_transparency:125,plot_text:"",is_net:0,vd_dire:1,show_window:1,window_head:2,window_text:"<id=12>出发迎接旅途的第一个挑战</id>",dire_shifting:{x:-150,y:-400,},};
		this.mConfigObject[27] = {key:27,step:3,cell:3,guide_desc:"点击第一英雄",trigger_type:1,guide_type:3,is_skip:1,direct_make:1,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:1,mask_transparency:125,plot_text:"",is_net:0,vd_dire:1,show_window:1,window_head:2,window_text:"<id=12>在这里点击头像放入队伍中</id>",dire_shifting:{x:-400,y:-250,},};
		this.mConfigObject[28] = {key:28,step:3,cell:4,guide_desc:"点击开战",trigger_type:1,guide_type:2,is_skip:1,direct_make:0,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:1,mask_transparency:125,plot_text:"",is_net:1,vd_dire:1,show_window:1,window_head:2,window_text:"<id=12>现在开始战斗！</id>",dire_shifting:{x:-300,y:-350,},};
		this.mConfigObject[29] = {key:29,step:3,cell:5,guide_desc:"战斗结束监听",trigger_type:1,guide_type:3,is_skip:1,direct_make:0,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:0,mask_transparency:0,plot_text:"",is_net:0,vd_dire:1,show_window:1,window_head:2,window_text:"<id=12>太棒了，首战就收获了稀有的技能资源，现在去给英雄装配吧</id>",dire_shifting:{x:0,y:0,},};
		this.mConfigObject[30] = {key:30,step:4,cell:1,guide_desc:"点击英雄",trigger_type:1,guide_type:3,is_skip:1,direct_make:0,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:1,mask_transparency:125,plot_text:"",is_net:0,vd_dire:1,show_window:1,window_head:2,window_text:"<id=12>主人，还记得怎么样装配技能吗，我们再来一次吧</id>",dire_shifting:{x:-400,y:-500,},};
		this.mConfigObject[31] = {key:31,step:4,cell:2,guide_desc:"点击冰海女巫",trigger_type:1,guide_type:3,is_skip:1,direct_make:1,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:1,mask_transparency:125,plot_text:"",is_net:0,vd_dire:1,show_window:1,window_head:2,window_text:"<id=12>点击查看英雄详情</id>",dire_shifting:{x:-350,y:0,},};
		this.mConfigObject[32] = {key:32,step:4,cell:3,guide_desc:"点击技能按钮",trigger_type:1,guide_type:3,is_skip:1,direct_make:1,mask_threshold:1,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:1,mask_transparency:125,plot_text:"",is_net:0,vd_dire:1,show_window:1,window_head:2,window_text:"<id=12>切换下方页签到技能页</id>",dire_shifting:{x:-150,y:-400,},};
		this.mConfigObject[33] = {key:33,step:4,cell:4,guide_desc:"装配技能",trigger_type:1,guide_type:3,is_skip:1,direct_make:1,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:1,mask_transparency:125,plot_text:"",is_net:0,vd_dire:1,show_window:1,window_head:2,window_text:"<id=12>把刚刚获取的技能装配上把</id>",dire_shifting:{x:-150,y:-50,},};
		this.mConfigObject[34] = {key:34,step:4,cell:5,guide_desc:"点击关闭",trigger_type:1,guide_type:2,is_skip:1,direct_make:1,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:0,mask_transparency:0,plot_text:"",is_net:0,vd_dire:1,show_window:0,window_head:2,window_text:"",dire_shifting:{x:0,y:0,},};
		this.mConfigObject[35] = {key:35,step:5,cell:1,guide_desc:"点击闯关",trigger_type:1,guide_type:3,is_skip:1,direct_make:0,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:1,mask_transparency:125,plot_text:"",is_net:0,vd_dire:1,show_window:1,window_head:2,window_text:"<id=12>激活技能的套装属性能够在战斗中获取更强的加成效果，继续下一步战斗，一路前进吧</id>",dire_shifting:{x:-250,y:-500,},};
		this.mConfigObject[36] = {key:36,step:5,cell:2,guide_desc:"点击挑战Boss",trigger_type:1,guide_type:3,is_skip:1,direct_make:1,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:1,mask_transparency:125,plot_text:"",is_net:0,vd_dire:1,show_window:1,window_head:2,window_text:"<id=12>点击挑战BOSS开始战斗</id>",dire_shifting:{x:-150,y:-400,},};
		this.mConfigObject[37] = {key:37,step:5,cell:3,guide_desc:"点击开战",trigger_type:1,guide_type:3,is_skip:1,direct_make:0,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:1,mask_transparency:125,plot_text:"",is_net:1,vd_dire:1,show_window:1,window_head:2,window_text:"<id=12>点击出战看看新技能威力吧！</id>",dire_shifting:{x:-300,y:-350,},};
		this.mConfigObject[38] = {key:38,step:5,cell:4,guide_desc:"战斗结束监听",trigger_type:1,guide_type:2,is_skip:1,direct_make:0,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:0,mask_transparency:0,plot_text:"",is_net:0,vd_dire:1,show_window:1,window_head:2,window_text:"<id=12>太棒了，现在去看看战利品吧</id>",dire_shifting:{x:-350,y:-450,},};
		this.mConfigObject[39] = {key:39,step:6,cell:1,guide_desc:"点击背包",trigger_type:1,guide_type:3,is_skip:1,direct_make:0,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:1,mask_transparency:125,plot_text:"",is_net:0,vd_dire:1,show_window:1,window_head:2,window_text:"<id=12>点击背包可以查看获取所有战利品</id>",dire_shifting:{x:-400,y:-500,},};
		this.mConfigObject[40] = {key:40,step:6,cell:2,guide_desc:"点击碎片页签",trigger_type:1,guide_type:3,is_skip:1,direct_make:1,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:1,mask_transparency:125,plot_text:"",is_net:0,vd_dire:1,show_window:1,window_head:2,window_text:"<id=12>以后还会获取很多的伙伴碎片都可以在这里查看</id>",dire_shifting:{x:-300,y:-400,},};
		this.mConfigObject[41] = {key:41,step:6,cell:3,guide_desc:"点击火爪灵猫碎片",trigger_type:1,guide_type:3,is_skip:1,direct_make:1,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:1,mask_transparency:125,plot_text:"",is_net:0,vd_dire:1,show_window:1,window_head:2,window_text:"<id=12>找到刚刚获取的火爪灵猫</id>",dire_shifting:{x:-400,y:-100,},};
		this.mConfigObject[42] = {key:42,step:6,cell:4,guide_desc:"点击合成",trigger_type:1,guide_type:3,is_skip:1,direct_make:1,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:1,mask_transparency:125,plot_text:"",is_net:0,vd_dire:1,show_window:1,window_head:2,window_text:"<id=12>点击合成赶快带走小伙伴吧</id>",dire_shifting:{x:-200,y:-250,},};
		this.mConfigObject[43] = {key:43,step:6,cell:5,guide_desc:"点击获得新英雄",trigger_type:1,guide_type:2,is_skip:1,direct_make:1,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:0,mask_transparency:0,plot_text:"",is_net:0,vd_dire:1,show_window:1,window_head:2,window_text:"<id=12>聪明机智的小火猫来了，以后就让我和您一起前进吧喵！</id>",dire_shifting:{x:-350,y:-500,},};
		this.mConfigObject[44] = {key:44,step:6,cell:6,guide_desc:"弹出大提示",trigger_type:1,guide_type:1,is_skip:1,direct_make:1,mask_threshold:0,vd_name:"<id=11>火爪灵猫</id>",vd_notify:"draw_HuoZhuaLingMao",vd_direction:{x:-100,y:80,scale:0.6,},finger:0,aperture:0,mask_transparency:0,plot_text:"<id=10>主人不要忘了给小火猫装配技能，这样我才能协助你作战，喵！</id>",is_net:0,vd_dire:1,show_window:0,window_head:2,window_text:"",dire_shifting:{x:0,y:0,},};
		this.mConfigObject[45] = {key:45,step:50,cell:1,guide_desc:"圣殿剧情",trigger_type:1,guide_type:1,is_skip:1,direct_make:0,mask_threshold:0,vd_name:"<id=11>冰海女巫</id>",vd_notify:"draw_aiEr",vd_direction:{x:150,y:100,scale:0.6,},finger:0,aperture:0,mask_transparency:0,plot_text:"<id=10>一定是在刚刚的战斗中无意触发了机关，相传这些闪闪发亮的能量物能够获取大量的宝物</id>",is_net:0,vd_dire:2,show_window:0,window_head:2,window_text:"",dire_shifting:{x:0,y:0,},};
		this.mConfigObject[46] = {key:46,step:50,cell:2,guide_desc:"圣殿剧情",trigger_type:1,guide_type:1,is_skip:1,direct_make:0,mask_threshold:0,vd_name:"<id=11>火爪灵猫</id>",vd_notify:"draw_HuoZhuaLingMao",vd_direction:{x:-100,y:80,scale:0.6,},finger:0,aperture:0,mask_transparency:0,plot_text:"<id=10>那太好了，主人我们的运气还是很不错的</id>",is_net:0,vd_dire:1,show_window:0,window_head:2,window_text:"",dire_shifting:{x:0,y:0,},};
		this.mConfigObject[47] = {key:47,step:50,cell:3,guide_desc:"圣殿剧情",trigger_type:1,guide_type:1,is_skip:1,direct_make:0,mask_threshold:0,vd_name:"<id=11>火爪灵猫</id>",vd_notify:"draw_HuoZhuaLingMao",vd_direction:{x:-100,y:80,scale:0.6,},finger:0,aperture:0,mask_transparency:0,plot_text:"<id=10>唉？怎么回事，地面一直摇晃我都站不稳了，救命啊主人！</id>",is_net:0,vd_dire:1,show_window:0,window_head:2,window_text:"",dire_shifting:{x:0,y:0,},};
		this.mConfigObject[48] = {key:48,step:50,cell:4,guide_desc:"圣殿剧情",trigger_type:1,guide_type:1,is_skip:1,direct_make:0,mask_threshold:0,vd_name:"<id=11>冰海女巫</id>",vd_notify:"draw_aiEr",vd_direction:{x:150,y:80,scale:0.6,},finger:0,aperture:0,mask_transparency:0,plot_text:"<id=10>应该是能量物与隐藏在此的传说宝库发生共鸣了，主人小心！</id>",is_net:0,vd_dire:2,show_window:0,window_head:2,window_text:"",dire_shifting:{x:0,y:0,},};
		this.mConfigObject[49] = {key:49,step:50,cell:5,guide_desc:"圣殿剧情",trigger_type:1,guide_type:3,is_skip:1,direct_make:0,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:1,mask_transparency:125,plot_text:"",is_net:0,vd_dire:1,show_window:1,window_head:2,window_text:"<id=12>圣殿功能开启了，我们一起查看吧</id>",dire_shifting:{x:-300,y:-450,},};
		this.mConfigObject[50] = {key:50,step:50,cell:6,guide_desc:"圣殿剧情",trigger_type:1,guide_type:1,is_skip:1,direct_make:0,mask_threshold:0,vd_name:"<id=11>冰海女巫</id>",vd_notify:"draw_aiEr",vd_direction:{x:150,y:100,scale:0.6,},finger:0,aperture:0,mask_transparency:0,plot_text:"<id=10>果然是这样，主人，刚刚那场战斗我们获取的能量物和这个远古的圣殿有关</id>",is_net:0,vd_dire:2,show_window:0,window_head:2,window_text:"",dire_shifting:{x:0,y:0,},};
		this.mConfigObject[51] = {key:51,step:50,cell:7,guide_desc:"圣殿剧情",trigger_type:1,guide_type:1,is_skip:1,direct_make:0,mask_threshold:0,vd_name:"<id=11>火爪灵猫</id>",vd_notify:"draw_HuoZhuaLingMao",vd_direction:{x:100,y:80,scale:0.6,},finger:0,aperture:0,mask_transparency:0,plot_text:"<id=10>这个你已经说过了，那这里到底是用来做什么的呢</id>",is_net:0,vd_dire:1,show_window:0,window_head:2,window_text:"",dire_shifting:{x:0,y:0,},};
		this.mConfigObject[52] = {key:52,step:50,cell:8,guide_desc:"圣殿剧情",trigger_type:1,guide_type:1,is_skip:1,direct_make:0,mask_threshold:0,vd_name:"<id=11>冰海女巫</id>",vd_notify:"draw_aiEr",vd_direction:{x:150,y:100,scale:0.6,},finger:0,aperture:0,mask_transparency:0,plot_text:"<id=10>相传，这里封印了远古历届魔界王的宝物，是一个类似宝库的地方，我们可以在这里获取很多宝器提升自己</id>",is_net:0,vd_dire:2,show_window:0,window_head:2,window_text:"",dire_shifting:{x:0,y:0,},};
		this.mConfigObject[53] = {key:53,step:50,cell:9,guide_desc:"圣殿剧情",trigger_type:1,guide_type:1,is_skip:1,direct_make:0,mask_threshold:0,vd_name:"<id=11>火爪灵猫</id>",vd_notify:"draw_HuoZhuaLingMao",vd_direction:{x:-100,y:80,scale:0.6,},finger:0,aperture:0,mask_transparency:0,plot_text:"<id=10>那么厉害！主人那我要很多宝物，然后帮助你赢得更多的战斗！</id>",is_net:0,vd_dire:1,show_window:0,window_head:2,window_text:"",dire_shifting:{x:0,y:0,},};
		this.mConfigObject[54] = {key:54,step:50,cell:10,guide_desc:"圣殿剧情",trigger_type:1,guide_type:1,is_skip:1,direct_make:0,mask_threshold:0,vd_name:"<id=11>冰海女巫</id>",vd_notify:"draw_aiEr",vd_direction:{x:150,y:80,scale:0.6,},finger:0,aperture:0,mask_transparency:0,plot_text:"<id=10>先别心急，我们先好好查看一下圣殿的结构</id>",is_net:0,vd_dire:2,show_window:0,window_head:2,window_text:"",dire_shifting:{x:0,y:0,},};
		this.mConfigObject[55] = {key:55,step:50,cell:11,guide_desc:"空白提示",trigger_type:1,guide_type:2,is_skip:1,direct_make:1,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:0,mask_transparency:125,plot_text:"",is_net:0,vd_dire:1,show_window:1,window_head:2,window_text:"<id=12>圣殿下方分为不同品质的魔能，旁边代表拥有魔能的数量</id>",dire_shifting:{x:-350,y:-450,},};
		this.mConfigObject[56] = {key:56,step:50,cell:12,guide_desc:"点击等级",trigger_type:1,guide_type:3,is_skip:1,direct_make:0,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:0,mask_transparency:125,plot_text:"",is_net:0,vd_dire:1,show_window:1,window_head:2,window_text:"<id=12>圣殿中心代表的是圣殿的等级，魔能充能时可获取经验，等级越高圣殿的物品也会越好</id>",dire_shifting:{x:-300,y:0,},};
		this.mConfigObject[57] = {key:57,step:50,cell:13,guide_desc:"点击返回",trigger_type:1,guide_type:2,is_skip:1,direct_make:1,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:0,mask_transparency:0,plot_text:"",is_net:0,vd_dire:1,show_window:1,window_head:2,window_text:"<id=12>再次点击空白返还圣殿</id>",dire_shifting:{x:-300,y:-250,},};
		this.mConfigObject[58] = {key:58,step:50,cell:14,guide_desc:"点击圣殿中心",trigger_type:1,guide_type:3,is_skip:1,direct_make:0,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:1,mask_transparency:0,plot_text:"",is_net:0,vd_dire:1,show_window:1,window_head:2,window_text:"<id=12>点击圣殿中心弹出四个宝物库</id>",dire_shifting:{x:-300,y:-250,},};
		this.mConfigObject[59] = {key:59,step:50,cell:15,guide_desc:"空白提示",trigger_type:1,guide_type:2,is_skip:1,direct_make:1,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:0,mask_transparency:125,plot_text:"",is_net:0,vd_dire:1,show_window:1,window_head:2,window_text:"<id=12>圣殿一共分为四个不同的宝物库，依次是：英雄，技能，装备，材料</id>",dire_shifting:{x:-300,y:-200,},};
		this.mConfigObject[60] = {key:60,step:50,cell:16,guide_desc:"点击第三个页签",trigger_type:1,guide_type:3,is_skip:1,direct_make:0,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:1,mask_transparency:125,plot_text:"",is_net:0,vd_dire:1,show_window:1,window_head:2,window_text:"<id=12>我们选中后可以点击魔能注入对应物品库中，这样就能产出对应库中的宝物，魔能品质越高，出现高级宝物的概率就越大！</id>",dire_shifting:{x:-350,y:-250,},};
		this.mConfigObject[61] = {key:61,step:50,cell:17,guide_desc:"点击魔能4注入",trigger_type:1,guide_type:3,is_skip:1,direct_make:0,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:1,mask_transparency:125,plot_text:"",is_net:0,vd_dire:1,show_window:1,window_head:2,window_text:"<id=12>点击放入刚刚获取的魔能，为圣殿充能</id>",dire_shifting:{x:-400,y:-450,},};
		this.mConfigObject[62] = {key:62,step:50,cell:18,guide_desc:"点击魔能4注入",trigger_type:1,guide_type:3,is_skip:1,direct_make:0,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:1,mask_transparency:125,plot_text:"",is_net:0,vd_dire:1,show_window:1,window_head:2,window_text:"<id=12>我们先放入四个魔能吧~</id>",dire_shifting:{x:-400,y:-450,},};
		this.mConfigObject[63] = {key:63,step:50,cell:19,guide_desc:"点击魔能4注入",trigger_type:1,guide_type:3,is_skip:1,direct_make:0,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:1,mask_transparency:125,plot_text:"",is_net:0,vd_dire:1,show_window:1,window_head:2,window_text:"<id=12>我们先放入四个魔能吧~</id>",dire_shifting:{x:-400,y:-450,},};
		this.mConfigObject[64] = {key:64,step:50,cell:20,guide_desc:"点击魔能4注入",trigger_type:1,guide_type:3,is_skip:1,direct_make:0,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:1,mask_transparency:125,plot_text:"",is_net:0,vd_dire:1,show_window:1,window_head:2,window_text:"<id=12>我们先放入四个魔能吧~</id>",dire_shifting:{x:-400,y:-450,},};
		this.mConfigObject[65] = {key:65,step:50,cell:21,guide_desc:"点击充能",trigger_type:1,guide_type:3,is_skip:1,direct_make:0,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:1,mask_transparency:125,plot_text:"",is_net:2,vd_dire:1,show_window:1,window_head:2,window_text:"<id=12>投入魔能后点击大门，会进入充能阶段</id>",dire_shifting:{x:-300,y:-250,},};
		this.mConfigObject[66] = {key:66,step:50,cell:22,guide_desc:"空白提示",trigger_type:1,guide_type:2,is_skip:1,direct_make:0,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:1,mask_transparency:125,plot_text:"",is_net:0,vd_dire:1,show_window:1,window_head:2,window_text:"<id=12>投入能量后圣殿充能需要等待一定的时间，一次投放的魔能越多，需要等待的时间也会对应增长哦</id>",dire_shifting:{x:-300,y:-250,},};
		this.mConfigObject[67] = {key:67,step:51,cell:1,guide_desc:"等待界面",trigger_type:1,guide_type:3,is_skip:2,direct_make:1,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:0,mask_transparency:0,plot_text:"",is_net:0,vd_dire:1,show_window:0,window_head:2,window_text:"",dire_shifting:{x:0,y:0,},};
		this.mConfigObject[68] = {key:68,step:51,cell:2,guide_desc:"倒计时界面",trigger_type:1,guide_type:3,is_skip:1,direct_make:1,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:1,mask_transparency:0,plot_text:"",is_net:0,vd_dire:1,show_window:1,window_head:2,window_text:"<id=12>进入倒计时阶段后，再次点击大门，可以弹出倒计时使用面板</id>",dire_shifting:{x:-300,y:-200,},};
		this.mConfigObject[69] = {key:69,step:51,cell:3,guide_desc:"使用加速券",trigger_type:1,guide_type:3,is_skip:1,direct_make:1,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:1,mask_transparency:125,plot_text:"",is_net:2,vd_dire:1,show_window:1,window_head:2,window_text:"<id=12>确认投放后，我们可以使用加速券来减少需要充能的时间</id>",dire_shifting:{x:-300,y:-200,},};
		this.mConfigObject[70] = {key:70,step:52,cell:1,guide_desc:"等待界面",trigger_type:1,guide_type:3,is_skip:2,direct_make:1,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:0,mask_transparency:0,plot_text:"",is_net:0,vd_dire:1,show_window:0,window_head:2,window_text:"",dire_shifting:{x:0,y:0,},};
		this.mConfigObject[71] = {key:71,step:52,cell:2,guide_desc:"收获物品",trigger_type:1,guide_type:3,is_skip:1,direct_make:1,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:1,mask_transparency:0,plot_text:"",is_net:0,vd_dire:1,show_window:1,window_head:2,window_text:"<id=12>成功减少了充能时间，现在点击圣殿收获物品，看看都有什么吧</id>",dire_shifting:{x:-300,y:-200,},};
		this.mConfigObject[72] = {key:72,step:52,cell:3,guide_desc:"监听弹窗",trigger_type:1,guide_type:2,is_skip:1,direct_make:1,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:0,mask_transparency:0,plot_text:"",is_net:2,vd_dire:1,show_window:0,window_head:2,window_text:"",dire_shifting:{x:0,y:0,},};
		this.mConfigObject[73] = {key:73,step:53,cell:1,guide_desc:"招募引导",trigger_type:1,guide_type:1,is_skip:1,direct_make:0,mask_threshold:0,vd_name:"<id=11>冰海女巫</id>",vd_notify:"draw_aiEr",vd_direction:{x:150,y:100,scale:0.6,},finger:0,aperture:0,mask_transparency:0,plot_text:"<id=10>主人，后面的路途只靠这些还不够，我们还需要更多的帮手，现在就去招募一些新英雄吧</id>",is_net:0,vd_dire:1,show_window:0,window_head:2,window_text:"",dire_shifting:{x:0,y:0,},};
		this.mConfigObject[74] = {key:74,step:53,cell:2,guide_desc:"点击主城",trigger_type:1,guide_type:3,is_skip:1,direct_make:1,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:1,mask_transparency:125,plot_text:"",is_net:0,vd_dire:1,show_window:1,window_head:2,window_text:"<id=12>现在我们点击前往主城，以后我们的很多行动都要在那里完成</id>",dire_shifting:{x:-400,y:-500,},};
		this.mConfigObject[75] = {key:75,step:53,cell:3,guide_desc:"点击抽卡",trigger_type:1,guide_type:3,is_skip:1,direct_make:0,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:1,mask_transparency:125,plot_text:"",is_net:0,vd_dire:1,show_window:1,window_head:2,window_text:"<id=12>通过主城的抽卡功能可以获取更多强有力的伙伴</id>",dire_shifting:{x:-300,y:100,},};
		this.mConfigObject[76] = {key:76,step:53,cell:4,guide_desc:"点击招募一次",trigger_type:1,guide_type:3,is_skip:1,direct_make:1,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:1,mask_transparency:125,plot_text:"",is_net:1,vd_dire:1,show_window:1,window_head:2,window_text:"<id=12>点击招募一次获取新的伙伴吧</id>",dire_shifting:{x:-350,y:-500,},};
		this.mConfigObject[77] = {key:77,step:53,cell:5,guide_desc:"宝石链接",trigger_type:1,guide_type:2,is_skip:1,direct_make:1,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:0,mask_transparency:0,plot_text:"",is_net:0,vd_dire:1,show_window:1,window_head:2,window_text:"<id=12>点击宝石将宝石全部连接汇集</id>",dire_shifting:{x:-150,y:-500,},};
		this.mConfigObject[78] = {key:78,step:53,cell:6,guide_desc:"获取英雄",trigger_type:1,guide_type:3,is_skip:1,direct_make:1,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:0,mask_transparency:0,plot_text:"",is_net:0,vd_dire:1,show_window:1,window_head:2,window_text:"<id=12>太好了多了一名新的伙伴</id>",dire_shifting:{x:-350,y:-500,},};
		this.mConfigObject[79] = {key:79,step:53,cell:7,guide_desc:"返回",trigger_type:1,guide_type:3,is_skip:1,direct_make:1,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:1,mask_transparency:125,plot_text:"",is_net:0,vd_dire:1,show_window:1,window_head:2,window_text:"<id=12>返回查看新英雄吧</id>",dire_shifting:{x:-350,y:-300,},};
		this.mConfigObject[80] = {key:80,step:53,cell:8,guide_desc:"返回",trigger_type:1,guide_type:3,is_skip:1,direct_make:1,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:1,mask_transparency:125,plot_text:"",is_net:0,vd_dire:1,show_window:1,window_head:2,window_text:"<id=12>返回查看新英雄吧</id>",dire_shifting:{x:-400,y:-450,},};
		this.mConfigObject[81] = {key:81,step:54,cell:1,guide_desc:"点击英雄",trigger_type:1,guide_type:3,is_skip:1,direct_make:0,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:0,mask_transparency:125,plot_text:"",is_net:0,vd_dire:1,show_window:1,window_head:2,window_text:"<id=12>主人，现在我们前往英雄界面用这些道具强化英雄吧</id>",dire_shifting:{x:-400,y:-500,},};
		this.mConfigObject[82] = {key:82,step:54,cell:2,guide_desc:"又多了一名伙伴",trigger_type:1,guide_type:3,is_skip:1,direct_make:0,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:1,mask_transparency:125,plot_text:"",is_net:0,vd_dire:1,show_window:1,window_head:2,window_text:"<id=12>又多了一名小伙伴，游戏内获取不同的英雄能激活不同的羁绊效果，能够有效的提高我们的作战能力</id>",dire_shifting:{x:-300,y:350,},};
		this.mConfigObject[83] = {key:83,step:54,cell:3,guide_desc:"若引导领取",trigger_type:1,guide_type:2,is_skip:1,direct_make:0,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:1,mask_transparency:125,plot_text:"",is_net:1,vd_dire:1,show_window:1,window_head:2,window_text:"<id=12>这里可以查看游戏内所有的羁绊效果还有激活条件，首次激活羁绊还有奖励物品</id>",dire_shifting:{x:-350,y:300,},};
		this.mConfigObject[84] = {key:84,step:55,cell:1,guide_desc:"点击英雄",trigger_type:1,guide_type:3,is_skip:2,direct_make:0,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:0,mask_transparency:0,plot_text:"",is_net:0,vd_dire:1,show_window:0,window_head:2,window_text:"",dire_shifting:{x:0,y:0,},};
		this.mConfigObject[85] = {key:85,step:55,cell:2,guide_desc:"选择新英雄",trigger_type:1,guide_type:3,is_skip:1,direct_make:1,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:1,mask_transparency:125,plot_text:"",is_net:0,vd_dire:1,show_window:1,window_head:2,window_text:"<id=12>下面我们点击新获取的英雄</id>",dire_shifting:{x:-200,y:0,},};
		this.mConfigObject[86] = {key:86,step:55,cell:3,guide_desc:"点击升级",trigger_type:1,guide_type:3,is_skip:1,direct_make:1,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:1,mask_transparency:125,plot_text:"",is_net:0,vd_dire:1,show_window:1,window_head:2,window_text:"<id=12>主人可以用刚刚获取的资源为新英雄升级</id>",dire_shifting:{x:-250,y:-400,},};
		this.mConfigObject[87] = {key:87,step:56,cell:1,guide_desc:"点击英雄按钮",trigger_type:1,guide_type:3,is_skip:3,direct_make:0,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:0,mask_transparency:0,plot_text:"",is_net:0,vd_dire:1,show_window:0,window_head:2,window_text:"",dire_shifting:{x:0,y:0,},};
		this.mConfigObject[88] = {key:88,step:56,cell:2,guide_desc:"点击新英雄",trigger_type:1,guide_type:3,is_skip:1,direct_make:1,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:1,mask_transparency:125,plot_text:"",is_net:0,vd_dire:1,show_window:1,window_head:2,window_text:"<id=12>下面我们点击新获取的英雄</id>",dire_shifting:{x:-200,y:0,},};
		this.mConfigObject[89] = {key:89,step:56,cell:3,guide_desc:"点击穿戴",trigger_type:1,guide_type:3,is_skip:1,direct_make:1,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:1,mask_transparency:125,plot_text:"",is_net:0,vd_dire:1,show_window:1,window_head:2,window_text:"<id=12>还有装备也给他穿上吧</id>",dire_shifting:{x:-250,y:-300,},};
		this.mConfigObject[90] = {key:90,step:56,cell:4,guide_desc:"空白提示",trigger_type:1,guide_type:2,is_skip:1,direct_make:1,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:1,mask_transparency:0,plot_text:"",is_net:0,vd_dire:1,show_window:1,window_head:2,window_text:"<id=12>主人也不要忘了要给新英雄添加刚获取的技能</id>",dire_shifting:{x:-150,y:-400,},};
		this.mConfigObject[91] = {key:91,step:80,cell:1,guide_desc:"剧情引导",trigger_type:1,guide_type:1,is_skip:1,direct_make:0,mask_threshold:0,vd_name:"<id=11>冰海女巫</id>",vd_notify:"draw_aiEr",vd_direction:{x:-150,y:100,scale:0.6,},finger:0,aperture:0,mask_transparency:0,plot_text:"<id=10>主人，获取新的伙伴后我们的实力又提升不少，现在可以去迎接下一场战斗了</id>",is_net:0,vd_dire:1,show_window:0,window_head:2,window_text:"",dire_shifting:{x:0,y:0,},};
		this.mConfigObject[92] = {key:92,step:80,cell:2,guide_desc:"剧情引导",trigger_type:1,guide_type:1,is_skip:1,direct_make:1,mask_threshold:0,vd_name:"<id=11>火爪灵猫</id>",vd_notify:"draw_HuoZhuaLingMao",vd_direction:{x:100,y:80,scale:0.6,},finger:0,aperture:0,mask_transparency:0,plot_text:"<id=10>对啊对啊，主人是最棒的！</id>",is_net:0,vd_dire:2,show_window:0,window_head:2,window_text:"",dire_shifting:{x:0,y:0,},};
		this.mConfigObject[93] = {key:93,step:80,cell:3,guide_desc:"剧情引导",trigger_type:1,guide_type:1,is_skip:1,direct_make:1,mask_threshold:0,vd_name:"<id=11>冰海女巫</id>",vd_notify:"draw_aiEr",vd_direction:{x:-150,y:100,scale:0.6,},finger:0,aperture:0,mask_transparency:0,plot_text:"<id=10>小火猫，你吓我一跳，看来你是个社牛体质的猫</id>",is_net:0,vd_dire:1,show_window:0,window_head:2,window_text:"",dire_shifting:{x:0,y:0,},};
		this.mConfigObject[94] = {key:94,step:80,cell:4,guide_desc:"剧情引导",trigger_type:1,guide_type:1,is_skip:1,direct_make:1,mask_threshold:0,vd_name:"<id=11>火爪灵猫</id>",vd_notify:"draw_HuoZhuaLingMao",vd_direction:{x:100,y:80,scale:0.6,},finger:0,aperture:0,mask_transparency:0,plot_text:"<id=10>社牛！什么是社牛？不过妖和妖之间的体质肯定是不一样的嘛</id>",is_net:0,vd_dire:2,show_window:0,window_head:2,window_text:"",dire_shifting:{x:0,y:0,},};
		this.mConfigObject[95] = {key:95,step:80,cell:5,guide_desc:"剧情引导",trigger_type:1,guide_type:1,is_skip:1,direct_make:1,mask_threshold:0,vd_name:"<id=11>火爪灵猫</id>",vd_notify:"draw_HuoZhuaLingMao",vd_direction:{x:100,y:80,scale:0.6,},finger:0,aperture:0,mask_transparency:0,plot_text:"<id=10>主人，我已经准备好了，本喵的实力一定会让你大吃一惊的！</id>",is_net:0,vd_dire:2,show_window:0,window_head:2,window_text:"",dire_shifting:{x:0,y:0,},};
		this.mConfigObject[96] = {key:96,step:100,cell:1,guide_desc:"天使引导",trigger_type:1,guide_type:1,is_skip:1,direct_make:0,mask_threshold:0,vd_name:"<id=11>冰海女巫</id>",vd_notify:"draw_aiEr",vd_direction:{x:-150,y:100,scale:0.6,},finger:0,aperture:0,mask_transparency:0,plot_text:"<id=10>前方有一股能量波动我去前方查看，主人小心</id>",is_net:0,vd_dire:1,show_window:0,window_head:2,window_text:"",dire_shifting:{x:0,y:0,},};
		this.mConfigObject[97] = {key:97,step:100,cell:2,guide_desc:"天使引导",trigger_type:1,guide_type:1,is_skip:1,direct_make:0,mask_threshold:0,vd_name:"<id=11>火爪灵猫</id>",vd_notify:"draw_HuoZhuaLingMao",vd_direction:{x:100,y:80,scale:0.6,},finger:0,aperture:0,mask_transparency:0,plot_text:"<id=10>感受到一股好强的能量喵</id>",is_net:0,vd_dire:2,show_window:0,window_head:2,window_text:"",dire_shifting:{x:0,y:0,},};
		this.mConfigObject[98] = {key:98,step:100,cell:3,guide_desc:"天使引导",trigger_type:1,guide_type:1,is_skip:1,direct_make:0,mask_threshold:0,vd_name:"<id=11>冰海女巫</id>",vd_notify:"draw_aiEr",vd_direction:{x:-150,y:100,scale:0.6,},finger:0,aperture:0,mask_transparency:0,plot_text:"<id=10>应该是远古的天使要苏醒了</id>",is_net:0,vd_dire:1,show_window:0,window_head:2,window_text:"",dire_shifting:{x:0,y:0,},};
		this.mConfigObject[99] = {key:99,step:100,cell:4,guide_desc:"点击天使",trigger_type:1,guide_type:3,is_skip:1,direct_make:0,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:1,mask_transparency:125,plot_text:"",is_net:0,vd_dire:1,show_window:1,window_head:2,window_text:"<id=12>天使快要苏醒</id>",dire_shifting:{x:-150,y:-450,},};
		this.mConfigObject[100] = {key:100,step:100,cell:5,guide_desc:"点击领取",trigger_type:1,guide_type:3,is_skip:1,direct_make:0,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:1,mask_transparency:0,plot_text:"",is_net:0,vd_dire:1,show_window:1,window_head:2,window_text:"<id=12>完成任务获取强力帮手</id>",dire_shifting:{x:-350,y:-100,},};
		this.mConfigObject[101] = {key:101,step:120,cell:1,guide_desc:"点击左侧切换",trigger_type:1,guide_type:3,is_skip:1,direct_make:0,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:1,mask_transparency:125,plot_text:"",is_net:0,vd_dire:1,show_window:1,window_head:2,window_text:"<id=12>天使苏醒了快去看看吧</id>",dire_shifting:{x:-400,y:-50,},};
		this.mConfigObject[102] = {key:102,step:120,cell:2,guide_desc:"点击升级",trigger_type:1,guide_type:3,is_skip:1,direct_make:0,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:1,mask_transparency:125,plot_text:"",is_net:0,vd_dire:1,show_window:1,window_head:2,window_text:"<id=12>这就是我们刚刚的天使了，点击升级让他更强吧</id>",dire_shifting:{x:-350,y:-300,},};
		this.mConfigObject[103] = {key:103,step:140,cell:1,guide_desc:"点击主城工会",trigger_type:1,guide_type:3,is_skip:1,direct_make:1,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:1,aperture:1,mask_transparency:125,plot_text:"",is_net:1,vd_dire:1,show_window:0,window_head:0,window_text:"",dire_shifting:{x:-350,y:-300,},};
		this.mConfigObject[104] = {key:104,step:140,cell:2,guide_desc:"空白提示",trigger_type:1,guide_type:4,is_skip:1,direct_make:1,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:1,mask_transparency:0,plot_text:"",is_net:0,vd_dire:1,show_window:1,window_head:2,window_text:"<id=12>主人也不要忘了要给新英雄添加刚获取的技能</id>",dire_shifting:{x:-150,y:-400,},};
		this.mConfigObject[105] = {key:105,step:160,cell:1,guide_desc:"首次进入工会",trigger_type:1,guide_type:4,is_skip:1,direct_make:1,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:1,mask_transparency:125,plot_text:"",is_net:1,vd_dire:1,show_window:1,window_head:2,window_text:"<id=12>主人也不要忘了要给新英雄添加刚获取的技能</id>",dire_shifting:{x:-150,y:-400,},};
		this.mConfigObject[106] = {key:106,step:160,cell:2,guide_desc:"空白提示",trigger_type:1,guide_type:4,is_skip:1,direct_make:1,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:1,mask_transparency:125,plot_text:"",is_net:0,vd_dire:1,show_window:1,window_head:2,window_text:"<id=12>主人也不要忘了要给新英雄添加刚获取的技能</id>",dire_shifting:{x:-150,y:-400,},};
		this.mConfigObject[107] = {key:107,step:180,cell:1,guide_desc:"通关奖励引导",trigger_type:1,guide_type:4,is_skip:1,direct_make:1,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:1,mask_transparency:125,plot_text:"",is_net:0,vd_dire:2,show_window:1,window_head:2,window_text:"<id=12>主人也不要忘了要给新英雄添加刚获取的技能</id>",dire_shifting:{x:-150,y:-400,},};
		this.mConfigObject[108] = {key:108,step:200,cell:1,guide_desc:"在线奖励引导",trigger_type:1,guide_type:4,is_skip:1,direct_make:1,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:1,mask_transparency:125,plot_text:"",is_net:0,vd_dire:2,show_window:1,window_head:2,window_text:"<id=12>主人也不要忘了要给新英雄添加刚获取的技能</id>",dire_shifting:{x:-150,y:-400,},};
		this.mConfigObject[109] = {key:109,step:220,cell:1,guide_desc:"首充引导",trigger_type:1,guide_type:4,is_skip:1,direct_make:1,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:1,mask_transparency:125,plot_text:"",is_net:0,vd_dire:2,show_window:1,window_head:2,window_text:"<id=12>主人也不要忘了要给新英雄添加刚获取的技能</id>",dire_shifting:{x:-150,y:-400,},};
		this.mConfigObject[110] = {key:110,step:240,cell:1,guide_desc:"升级有礼引导",trigger_type:1,guide_type:4,is_skip:1,direct_make:1,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:1,mask_transparency:125,plot_text:"",is_net:0,vd_dire:2,show_window:1,window_head:2,window_text:"<id=12>主人也不要忘了要给新英雄添加刚获取的技能</id>",dire_shifting:{x:-150,y:-400,},};
		this.mConfigObject[111] = {key:111,step:260,cell:1,guide_desc:"成长之路引导",trigger_type:1,guide_type:4,is_skip:1,direct_make:1,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:1,mask_transparency:125,plot_text:"",is_net:1,vd_dire:2,show_window:1,window_head:2,window_text:"<id=12>主人也不要忘了要给新英雄添加刚获取的技能</id>",dire_shifting:{x:-150,y:-400,},};
		this.mConfigObject[112] = {key:112,step:260,cell:2,guide_desc:"成长之路引导",trigger_type:1,guide_type:4,is_skip:1,direct_make:1,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:1,mask_transparency:125,plot_text:"",is_net:0,vd_dire:2,show_window:1,window_head:2,window_text:"<id=12>主人也不要忘了要给新英雄添加刚获取的技能</id>",dire_shifting:{x:-150,y:-400,},};
		this.mConfigObject[113] = {key:113,step:260,cell:3,guide_desc:"成长之路引导",trigger_type:1,guide_type:4,is_skip:1,direct_make:1,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:1,mask_transparency:125,plot_text:"",is_net:0,vd_dire:2,show_window:1,window_head:2,window_text:"<id=12>主人也不要忘了要给新英雄添加刚获取的技能</id>",dire_shifting:{x:-150,y:-400,},};
		this.mConfigObject[114] = {key:114,step:280,cell:1,guide_desc:"八日登录引导",trigger_type:1,guide_type:4,is_skip:1,direct_make:1,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:1,mask_transparency:125,plot_text:"",is_net:0,vd_dire:2,show_window:1,window_head:2,window_text:"<id=12>主人也不要忘了要给新英雄添加刚获取的技能</id>",dire_shifting:{x:-150,y:-400,},};
		this.mConfigObject[115] = {key:115,step:300,cell:1,guide_desc:"任务引导",trigger_type:1,guide_type:4,is_skip:1,direct_make:1,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:1,mask_transparency:125,plot_text:"",is_net:0,vd_dire:2,show_window:1,window_head:2,window_text:"<id=12>主人也不要忘了要给新英雄添加刚获取的技能</id>",dire_shifting:{x:-150,y:-400,},};
		this.mConfigObject[116] = {key:116,step:320,cell:1,guide_desc:"VIP引导",trigger_type:1,guide_type:4,is_skip:1,direct_make:1,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:1,mask_transparency:125,plot_text:"",is_net:0,vd_dire:2,show_window:1,window_head:2,window_text:"<id=12>主人也不要忘了要给新英雄添加刚获取的技能</id>",dire_shifting:{x:-150,y:-400,},};
		this.mConfigObject[117] = {key:117,step:340,cell:1,guide_desc:"祭坛引导",trigger_type:1,guide_type:4,is_skip:1,direct_make:1,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:1,mask_transparency:125,plot_text:"",is_net:0,vd_dire:2,show_window:1,window_head:2,window_text:"<id=12>主人也不要忘了要给新英雄添加刚获取的技能</id>",dire_shifting:{x:-150,y:-400,},};
		this.mConfigObject[118] = {key:118,step:360,cell:1,guide_desc:"水晶引导",trigger_type:1,guide_type:4,is_skip:1,direct_make:1,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:1,mask_transparency:125,plot_text:"",is_net:1,vd_dire:2,show_window:1,window_head:2,window_text:"<id=12>主人也不要忘了要给新英雄添加刚获取的技能</id>",dire_shifting:{x:-150,y:-400,},};
		this.mConfigObject[119] = {key:119,step:360,cell:2,guide_desc:"水晶引导",trigger_type:1,guide_type:4,is_skip:1,direct_make:1,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:1,mask_transparency:125,plot_text:"",is_net:0,vd_dire:2,show_window:1,window_head:2,window_text:"<id=12>主人也不要忘了要给新英雄添加刚获取的技能</id>",dire_shifting:{x:-150,y:-400,},};
		this.mConfigObject[120] = {key:120,step:360,cell:3,guide_desc:"水晶引导",trigger_type:1,guide_type:4,is_skip:1,direct_make:1,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:1,mask_transparency:125,plot_text:"",is_net:0,vd_dire:2,show_window:1,window_head:2,window_text:"<id=12>主人也不要忘了要给新英雄添加刚获取的技能</id>",dire_shifting:{x:-150,y:-400,},};
		this.mConfigObject[121] = {key:121,step:360,cell:4,guide_desc:"水晶引导",trigger_type:1,guide_type:4,is_skip:1,direct_make:1,mask_threshold:0,vd_name:"",vd_notify:"",vd_direction:{x:0,y:0,scale:0,},finger:0,aperture:1,mask_transparency:125,plot_text:"",is_net:0,vd_dire:2,show_window:1,window_head:2,window_text:"<id=12>主人也不要忘了要给新英雄添加刚获取的技能</id>",dire_shifting:{x:-150,y:-400,},};
    }
    private InitArray(){
        for(let key in this.mConfigObject){
            this.mConfigArray.push(this.mConfigObject[key]);
        }
    }
    public GetLen(){
        return this.mConfigArray.length;
    }
    public GetData(key:number): INewGuideConfigStruct | undefined{
        return this.mConfigObject[key];
    } 
    public GetDatas():Readonly<Array<INewGuideConfigStruct>>{
        return this.mConfigArray;
    }
};
export let NewGuideConfigConfig:NewGuideConfig = new NewGuideConfig();
